# Copyright (c) 2015-2021 Contributors to the Eclipse Foundation
# 
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
# 
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
# 
# SPDX-License-Identifier: EPL-2.0
#

#Choose a base image that matches the type of build we are using...
#By default we use: centos7
#FROM quay.io/centos/centos:7
# For a RHEL8/CentOS8 distro, we use AlmaLinux:
FROM quay.io/almalinuxorg/8-base:8
# For Fedora, the verion changes very often due to their short life
#FROM quay.io/fedora/fedora:35-x86_64

ARG IMAUSER=imarun

# create users and groups
RUN groupadd -g 1000 $IMAUSER \
    && useradd -m $IMAUSER -u 1000 -g $IMAUSER -G wheel -d /home/${IMAUSER}  \
    && echo "alias ll='ls -alF'" >> /home/${IMAUSER}/.bashrc

WORKDIR /usr/share/amlen-server/bin

# Install packages
#RUN yum -y update

RUN yum -y install gdb net-tools openssh-clients openssl tar perl jansson zip logrotate bzip2 unzip

COPY EclipseAmlenServer-1.0.0.2-20250129.0843_build.almalinux8.x86_64.rpm /tmp/imaserver.rpm

RUN yum -y localinstall /tmp/imaserver.rpm

RUN rm -f /tmp/imaserver.rpm

ENV LD_LIBRARY_PATH=/usr/lib64

#USER $IMAUSER:$IMAUSER

ENTRYPOINT [ "/usr/share/amlen-server/bin/startServer.sh" ]